### ISSUE TITLE
How to style with card mod?

### ISSUE THREAD

**Issue by sashalondon** [decompil3d/lovelace-hourly-weather#112]
I am using your weather bar and am integrating it into a mushroom-themed dashboard. 

(https://github.com/piitaya/lovelace-mushroom)

I have styled the card to match the mushroom aesthetic but wanted to know if it is possible to edit the bar or text with the card mod app in home assistant. I have an image of what I have made and what I want to match plus the code I have used. I do not know it this is a feature request as in you would implement the possibility of moding the design or if you could give some advice on the lines to mod the configuration, please?
I am trying to change the radius and transparency of the bar and the font style/size of the text (in the bar and under the bar).

Mushroom light
![mushroom light](https://user-images.githubusercontent.com/8496722/185401290-c8b08e8c-728d-418a-98a0-fc616f21a344.png)

Design so far
![fd3e33aabe9b6ab686ee1f83cf483a4a14ddae3e_2_690x252](https://user-images.githubusercontent.com/8496722/185401319-c20443a0-aaed-4e62-9f0a-2ae705830d74.png)

```yaml
type: custom:stack-in-card
cards:
  - type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: 42px auto
      margin: '-4px -4px -12px -4px;'
    cards:
      - type: custom:mushroom-template-card
        entity: sensor.openweathermap_condition
        icon: mdi:weather-cloudy
        icon_color: yellow
        card_mod:
          style: |
            ha-card {
              background: none;
              --ha-card-box-shadow: 0px;
            }
      - type: custom:hourly-weather
        entity: weather.openweathermap
        icons: false
        label_spacing: '2'
        num_segments: '12'
        name: ' '
        card_mod:
          style: |
            ha-card {
              padding: 0px;
              margin-left: 12px;
              --bar-card-border-radius: 12px;
              --mush-rgb-red: 244, 67, 54;
              --mush-rgb-pink: 233, 30, 99;
              --mush-rgb-purple: 156, 39, 176;
              --mush-rgb-deep-purple: 103, 58, 183;
              --mush-rgb-indigo: 63, 81, 181;
              --mush-rgb-blue: 33, 150, 243;
              --mush-rgb-light-blue: 3, 169, 244;
              --mush-rgb-cyan: 0, 188, 212;
              --mush-rgb-teal: 0, 150, 136;
              --mush-rgb-green: 76, 175, 80;
              --mush-rgb-light-green: 139, 195, 74;
              --mush-rgb-lime: 205, 220, 57;
              --mush-rgb-yellow: 255, 235, 59;
              --mush-rgb-amber: 255, 193, 7;
              --mush-rgb-orange: 255, 152, 0;
              --mush-rgb-deep-orange: 255, 87, 34;
              --mush-rgb-brown: 121, 85, 72;
              --mush-rgb-grey: 158, 158, 158;
              --mush-rgb-blue-grey: 96, 125, 139;
              --mush-rgb-black: 0, 0, 0;
              --mush-rgb-white: 255, 255, 255;
            }
            hour {
              margin: 12px;
              font-size: 12px;
              font-weight: bolder;
            }
            temperature {
              margin: 12px;
              font-size: 12px;
              font-weight: bolder;
            }
            bar-backgroundbar {
              opacity: 0.9;
              filter: brightness(1);
            }
```

**Comment by decompil3d** [comment]
As you may already know, Home Assistant's dashboard system makes heavy use of WebComponents and thus ShadowDOM. `card-mod` has [good support](https://github.com/thomasloven/lovelace-card-mod#dom-navigation) for ShadowDOM navigation through their `$` keyword.

In the case of this hourly weather card, I use two layers of WebComponents, which is why your initial attempt isn't quite working. The outer card, title, and any warnings/errors are rendered at the top level while the bar and axes are rendered within a `weather-bar` component.

So, to style things like the hour elements, you'd do something like:

```yaml
card_mod:
  style:
    .: |
      ha-card {
        /* whatever styles you want on the card itself */
      }
    weather-bar$: |
      .hour {
        margin: 12px;
        font-size: 12px;
        font-weight: bolder;
      }
```

Hope this helps. I'll close the issue as it's not a bug, but feel free to comment further if you need more help.

**Comment by Sku4l** [comment]
Thank you decompil3d for the help.

@sashalondon did you manage to do what you wanted? I am really bad at css and even worse with card-mod.. could you share your result if you managed to do so?
I cannot seem to change the height of the ".bar" no matter what I try, it remains fixed to 30px

**Comment by decompil3d** [comment]
@Sku4l Here you go:

```yaml
card_mod:
  style:
    weather-bar$: |
      .bar, .bar > div {
        height: 50px !important;
      }
````

**Comment by Valdorama** [comment]
Based on the selected background colours for the weather bars, the text can often appear lost because of the text shadow. I've tried slightly darker colours for the text but again the shadow gets in the way. 

Can you please tell me what card_mod path/syntax to use to set the 'text-shadow' attribute on the 'condition-label' elements?

**Comment by decompil3d** [comment]
> Based on the selected background colours for the weather bars, the text can often appear lost because of the text shadow. I've tried slightly darker colours for the text but again the shadow gets in the way.
> 
> Can you please tell me what card_mod path/syntax to use to set the 'text-shadow' attribute on the 'condition-label' elements?

```yaml
card_mod:
  style:
    weather-bar$: |
      .condition-label {
        text-shadow: none !important;
      }
```

The `!important` is important (no pun intended) since it has to override the style tag that lit outputs. You can set it to whatever you want, not just `none`.
