### ISSUE TITLE
[FR] Colors: Allow CSS variables

### ISSUE THREAD

**Issue by uvjim** [decompil3d/lovelace-hourly-weather#165]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but when using the `colors` object to define colors for weather conditions it'd be great to allow CSS variables. I could then use variables specified by a theme (Mushroom, built-in etc). Currently using a variable doesn't pass validation for the card.

Passes validation:
```yaml
colors:
  rainy: rgba(33, 150, 243, 0.5)
  cloudy: rgb(158, 158, 158, 0.5)
```
Fails validation:
```yaml
colors:
  rainy: rgba(var(--mush-rgb-grey), 0.5)
  cloudy: rgb(var(--mush-rgb-blue-grey), 0.5)
```

**Describe the solution you'd like**
CSS variables to be used for items in the `colors` object.

**Describe alternatives you've considered**
Using `card-mod` to apply the colors instead of the object.
