### ISSUE TITLE
Support of weather entites with multiple entites (e.g. Deutscher Wetterdienst / German weather service)

### ISSUE THREAD

**Issue by Maxtropos** [decompil3d/lovelace-hourly-weather#189]
**Is your feature request related to a problem? Please describe.**

I'm currently using the DWD (Deutscher Wetterdienst / German weather service) integration, which uses a forecast-object in its state. For hourly forecasts it uses an entity per attribute. So there is an sensor.temperature, sensor.humidty, sensor.precipitation, etc.
Is ist possible to include those multiple entites to the card? Currently I can only add the weather. entity, which do not provide hourly forecast.

**Describe the solution you'd like**
Is ist possible to include those multiple entites to the card? Currently I can only add the weather. entity, which do not provide hourly forecast.

**Describe alternatives you've considered**
I did not find any

**Additional context**
The entity states look like this:

### sensor.humidity
```
state_class: measurement
data: 
- datetime: '2022-10-19T20:00:00.000Z'
  value: 100
- datetime: '2022-10-19T21:00:00.000Z'
  value: 98.6
- datetime: '2022-10-19T22:00:00.000Z'
  value: 98.6
- datetime: '2022-10-19T23:00:00.000Z'
  value: 98.6
- datetime: '2022-10-20T00:00:00.000Z'
  value: 96.6
- datetime: '2022-10-20T01:00:00.000Z'
  value: 95.2

..... etc etc

forecast_time_utc: 2022-10-19T15:00:00+00:00
latest_update_utc: 2022-10-19T20:00:26.001705+00:00
station_id: ****
station_name: ****
attribution: Data provided by Deutscher Wetterdienst (DWD)
unit_of_measurement: %
device_class: humidity
icon: mdi:water-percent
friendly_name: Luftfeuchtigkeit
```

### sensor.temperature
```

state_class: measurement
data: 
- datetime: '2022-10-19T20:00:00.000Z'
  value: 5.5
- datetime: '2022-10-19T21:00:00.000Z'
  value: 5.2
- datetime: '2022-10-19T22:00:00.000Z'
  value: 4.9
- datetime: '2022-10-19T23:00:00.000Z'
  value: 4.8
- datetime: '2022-10-20T00:00:00.000Z'
  value: 4.8
- datetime: '2022-10-20T01:00:00.000Z'
  value: 4.5
- datetime: '2022-10-20T02:00:00.000Z'
  value: 4.3
- datetime: '2022-10-20T03:00:00.000Z'
  value: 4.3
- datetime: '2022-10-20T04:00:00.000Z'
  value: 4.3

..... etc etc

forecast_time_utc: 2022-10-19T15:00:00+00:00
latest_update_utc: 2022-10-19T20:00:26.001705+00:00
station_id: ***
station_name: ***
attribution: Data provided by Deutscher Wetterdienst (DWD)
unit_of_measurement: °C
device_class: temperature
icon: mdi:temperature-celsius
friendly_name: Temperatur

```
