### ISSUE TITLE
Unable to change 'hour' font color and size

### ISSUE THREAD

**Issue by vhardono** [decompil3d/lovelace-hourly-weather#357]
I tried to change 'hour' font color, size and margin following suggestion from previous closed issue. After applying the script change, only margin changed, however font size, color, weight remain the same. would you be able to advise what is wrong with my script?
Thanks!

                    card_mod:
                      style:
                        .: |
                          ha-card {
                            border: none;
                            background: none;
                            color: rgba(248, 248, 248, 0.8);
                          }
                        weather-bar$: |
                          .hour {
                            margin: 30px;
                            font-weight: bold;
                            size: 30px;
                            color: rgba(248, 248, 248, 0.8);
                          }

              As you may already know, Home Assistant's dashboard system makes heavy use of WebComponents and thus ShadowDOM. `card-mod` has [good support](https://github.com/thomasloven/lovelace-card-mod#dom-navigation) for ShadowDOM navigation through their `$` keyword.

In the case of this hourly weather card, I use two layers of WebComponents, which is why your initial attempt isn't quite working. The outer card, title, and any warnings/errors are rendered at the top level while the bar and axes are rendered within a `weather-bar` component.

So, to style things like the hour elements, you'd do something like:

```yaml
card_mod:
  style:
    .: |
      ha-card {
        /* whatever styles you want on the card itself */
      }
    weather-bar$: |
      .hour {
        margin: 12px;
        font-size: 12px;
        font-weight: bolder;
      }
```

Hope this helps. I'll close the issue as it's not a bug, but feel free to comment further if you need more help.

_Originally posted by @decompil3d in https://github.com/decompil3d/lovelace-hourly-weather/issues/112#issuecomment-1222727029_
