### ISSUE TITLE
Doesn't respect border radius adjustmts from stack-in-card

### ISSUE THREAD

**Issue by ex-nerd** [decompil3d/lovelace-hourly-weather#407]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

`4.11.0`

**Last working release (if known):**

🤷‍♂️

**Browser and Operating System:**

- latest versions of MacOS with Chrome and Safari
- latest iOS version of Home Assistant app

**Description of problem:**

I know this is an interaction between two third-party cards, but yours is the first I've seen that doesn't play nice with https://github.com/custom-cards/stack-in-card

I'm trying to create a nicely stacked weather card with the regular and hourly forecasts together. Config is:

```yaml
type: custom:stack-in-card
mode: vertical
keep:
  background: true
  border_radius: false
  margin: false
cards:
  - type: weather-forecast
    show_current: true
    show_forecast: true
    entity: weather.forecast_home
  - type: custom:hourly-weather
    entity: weather.forecast_home_hourly
    show_precipitation_amounts: true
    show_precipitation_probability: true
    icons: true
    name: null
    show_wind: 'true'
```

This results in a card that looks like:

<img width="511" alt="Screenshot 2023-06-01 at 2 33 55 PM" src="https://github.com/decompil3d/lovelace-hourly-weather/assets/154074/b18d6f99-25fb-435f-b277-47d1c0e93ce2">

You'll notice that the built-in weather card loses its rounded borders at the bottom, creating a more seamless stack, but the hourly weather card retains its rounded borders at the top.

I dug around a bit in the CSS and didn't see anything glaring, and I can fix it with `card-mod` by applying a style override to the hour-weather card:

```yaml
    style: |
      ha-card {
        border-radius: 0px;
      }
```

Anyway, not a serious issue but wanted to at least document the workaround here in case anyone else runs into it.
