### ISSUE TITLE
Font style configuration

### ISSUE THREAD

**Issue by janick** [decompil3d/lovelace-hourly-weather#485]
Love the card!

**Is your feature request related to a problem? Please describe.**
The forecast values are a little small on my wall console. I would you like to increase them.

**Describe the solution you'd like**
Either an option to set various forecast values font styles, or document the scopes and style names that should be used in card-mod.

**Describe alternatives you've considered**

**Additional context**

**Comment by decompil3d** [comment]
You can use card-mod like so:

```yaml
card_mod:
  style:
    weather-bar$: |
      .hour {
        font-size: 2rem !important
      }
```

Classes to target include:
- `date`
- `hour`
- `temperature`
- `wind`
- `precipitation`

Hope this helps!
