### ISSUE TITLE
Add humidity

### ISSUE THREAD

**Issue by bpinney** [decompil3d/lovelace-hourly-weather#525]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I would love to see the humidity presented along with temperature in each segment on the bar.

**Describe alternatives you've considered**
None

**Additional context**
I imagine this would be optional, just like wind and precipitation. My current weather integration is tomorrow.io, which has the following properties for the daily entity:
```
temperature: 69
temperature_unit: °F
humidity: 79
pressure: 30.23
pressure_unit: inHg
wind_bearing: 37.5
wind_speed: 10.92
wind_speed_unit: mph
visibility: 9.22
visibility_unit: mi
precipitation_unit: in
forecast: 
- datetime: '2023-09-26T12:00:00+00:00'
  condition: cloudy
  precipitation_probability: 4
  wind_bearing: 26.1
  temperature: 69
  templow: 65
  dew_point: 56
  wind_speed: 14.73
  precipitation: 0.16
  humidity: 91
```
