### ISSUE TITLE
Allow sub-hourly forecast

### ISSUE THREAD

**Issue by Tommatheussen** [decompil3d/lovelace-hourly-weather#60]
**Is your feature request related to a problem? Please describe.**
The [Tomorrow.io](https://www.home-assistant.io/integrations/tomorrowio/) integration allows forecasts in intervals less than 1 hour (1 minute, 5 minute or 15 minute). It would be nice if this was possible to be shown

**Describe the solution you'd like**
Actually, this used to work with version 3.0.0, but it seems to update to larger forecast intervals (3.1.0) broke this behavior, it doesn't show an error during configuration or anything, it just doesn't show anything :)

**Describe alternatives you've considered**
/

**Additional context**
If it helps, these are the attributes set the integration, with forecast intervals for 15minutes:
<details>
  <summary>View attributes</summary>
  
```
temperature: 15.2
temperature_unit: °C
humidity: 69
pressure: 1022.38
pressure_unit: hPa
wind_bearing: 350.63
wind_speed: 8.57
wind_speed_unit: km/h
visibility: 16
visibility_unit: km
precipitation_unit: mm
forecast: 
- datetime: '2022-07-14T21:00:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 350.63
  temperature: 15.2
  wind_speed: 8.57
  precipitation: 0
- datetime: '2022-07-14T21:15:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 350.63
  temperature: 14.8
  wind_speed: 8.14
  precipitation: 0
- datetime: '2022-07-14T21:30:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 345.48
  temperature: 14.4
  wind_speed: 7.7
  precipitation: 0
- datetime: '2022-07-14T21:45:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 345.48
  temperature: 14
  wind_speed: 7.27
  precipitation: 0
- datetime: '2022-07-14T22:00:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 345.48
  temperature: 13.6
  wind_speed: 6.88
  precipitation: 0
- datetime: '2022-07-14T22:15:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 345.48
  temperature: 13.3
  wind_speed: 6.55
  precipitation: 0
- datetime: '2022-07-14T22:30:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 341.09
  temperature: 13.1
  wind_speed: 6.26
  precipitation: 0
- datetime: '2022-07-14T22:45:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 341.09
  temperature: 12.8
  wind_speed: 5.94
  precipitation: 0
- datetime: '2022-07-14T23:00:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 341.09
  temperature: 12.6
  wind_speed: 5.65
  precipitation: 0
- datetime: '2022-07-14T23:15:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 341.09
  temperature: 12.3
  wind_speed: 5.36
  precipitation: 0
- datetime: '2022-07-14T23:30:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 333.01
  temperature: 12.1
  wind_speed: 5.08
  precipitation: 0
- datetime: '2022-07-14T23:45:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 333.01
  temperature: 11.9
  wind_speed: 4.79
  precipitation: 0
- datetime: '2022-07-15T00:00:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 333.01
  temperature: 11.7
  wind_speed: 4.5
  precipitation: 0
- datetime: '2022-07-15T00:15:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 333.01
  temperature: 11.5
  wind_speed: 4.36
  precipitation: 0
- datetime: '2022-07-15T00:30:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 318.01
  temperature: 11.4
  wind_speed: 4.18
  precipitation: 0
- datetime: '2022-07-15T00:45:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 318.01
  temperature: 11.2
  wind_speed: 4.03
  precipitation: 0
- datetime: '2022-07-15T01:00:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 318.01
  temperature: 11.1
  wind_speed: 3.85
  precipitation: 0
- datetime: '2022-07-15T01:15:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 318.01
  temperature: 11
  wind_speed: 3.82
  precipitation: 0
- datetime: '2022-07-15T01:30:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 309.11
  temperature: 10.8
  wind_speed: 3.78
  precipitation: 0
- datetime: '2022-07-15T01:45:00+00:00'
  condition: clear-night
  precipitation_probability: 0
  wind_bearing: 309.11
  temperature: 10.7
  wind_speed: 3.74
  precipitation: 0
- datetime: '2022-07-15T02:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 309.11
  temperature: 10.6
  wind_speed: 3.67
  precipitation: 0
- datetime: '2022-07-15T02:15:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 309.11
  temperature: 10.5
  wind_speed: 3.53
  precipitation: 0
- datetime: '2022-07-15T02:30:00+00:00'
  condition: cloudy
  precipitation_probability: 0
  wind_bearing: 306.39
  temperature: 10.4
  wind_speed: 3.38
  precipitation: 0
- datetime: '2022-07-15T02:45:00+00:00'
  condition: cloudy
  precipitation_probability: 0
  wind_bearing: 306.39
  temperature: 10.4
  wind_speed: 3.24
  precipitation: 0
- datetime: '2022-07-15T03:00:00+00:00'
  condition: cloudy
  precipitation_probability: 0
  wind_bearing: 306.39
  temperature: 10.3
  wind_speed: 3.06
  precipitation: 0
- datetime: '2022-07-15T03:15:00+00:00'
  condition: cloudy
  precipitation_probability: 0
  wind_bearing: 306.39
  temperature: 10.3
  wind_speed: 2.92
  precipitation: 0
- datetime: '2022-07-15T03:30:00+00:00'
  condition: cloudy
  precipitation_probability: 0
  wind_bearing: 291.33
  temperature: 10.2
  wind_speed: 2.77
  precipitation: 0
- datetime: '2022-07-15T03:45:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  wind_bearing: 291.33
  temperature: 10.2
  wind_speed: 2.59
  precipitation: 0
- datetime: '2022-07-15T04:00:00+00:00'
  condition: sunny
  precipitation_probability: 0
  wind_bearing: 291.33
  temperature: 10.2
  wind_speed: 2.45
  precipitation: 0
- datetime: '2022-07-15T04:15:00+00:00'
  condition: sunny
  precipitation_probability: 0
  wind_bearing: 291.33
  temperature: 10.4
  wind_speed: 2.52
  precipitation: 0

attribution: Powered by Tomorrow.io
friendly_name: Tomorrow.io - Home - Nowcast
```

</details>
