### ISSUE TITLE
background color with vertical stack in cards

### ISSUE THREAD

**Issue by djsomi** [decompil3d/lovelace-hourly-weather#608]
Hi All,

I am using this card with vertical stack in cards. [https://github.com/ofekashery/vertical-stack-in-card](url)
There is a problem with the background, card gets double bg opacity when stacked into together.

![vertical](https://github.com/decompil3d/lovelace-hourly-weather/assets/19391031/01146bdf-2578-4473-9411-61ac895b4e5b)

Can you help me how to get rid of this?

Many Thanks
Zoltan

**Comment by mogim0gi** [comment]
having same issue

**Comment by decompil3d** [comment]
You can use card-mod to remove the card background:

```yaml
card_mod:
  style:
    .: |
      ha-card {
        background-color: transparent;
        box-shadow: none;
      }
```
