### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by Francois3d** [decompil3d/lovelace-hourly-weather#796]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
IT would be great if you can set the background of the card transparent or to a colour of your choosing. see example of upload screenshot of custom button card that has transparent background:  Configured as below

styles:
  card:
    - background: var(--contrast1)

**Describe alternatives you've considered**
Thinking of using custom button card to provide hourly weather forecast

**Additional context**

![Image](https://github.com/user-attachments/assets/97ca880a-92f6-4422-b45b-84de8e1cc375)

**Comment by guensen0** [comment]
same for me...

**Comment by decompil3d** [comment]
This card uses `ha-card` under the hood, so you can use card-mod to achieve this:

```yaml
card_mod:
  style:
    .: |
      ha-card {
        background-color: transparent;
        box-shadow: none;
      }
```
